import router from '@system.router';
export default {
    data: {
        videolist:[
            {
                id:1,
                name:'我的家乡',
                url:[
                {
                    id:1,
                    url:'/common/moves/er.jpg',
                    video:'/common/video/v2020092753HU3HOWBBZ6LOXT.mp4'
                },
                {
                    id:2,
                    url:'/common/moves/hah.jpg',
                    video:'/common/video/v20200924A1BQU4KBW6EQ30JH.mp4'
                },
                {
                    id:3,
                    url:'/common/moves/xixi.jpg',
                    video:'/common/video/402650673.mp4'
                },
                {
                    id:4,
                    url:'/common/moves/ooo.jpg',
                    video:'/common/video/402660269.mp4'
                }
                ],
                itemname:'相关视频',

                items:[
                    {
                        id:1,
                        url:'/common/moves/hah.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:2,
                        url:'/common/moves/er.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:3,
                        url:'/common/moves/ooo.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    }

                ]
            },
            {
                id:2,
                name:'你的家乡',
                itemname:'相关视频',
                url:[
                    {
                        id:1,
                        url:'/common/moves/hah.jpg',
                        video:'/common/video/402660270.mp4'
                    },
                    {
                        id:2,
                        url:'/common/moves/rr.jpg',
                        video:'/common/video/402660575.mp4'
                    },
                    {
                        id:3,
                        url:'/common/moves/xixi.jpg',
                        video:''
                    },
                    {
                        id:4,
                        url:'/common/moves/ooo.jpg',
                    }
                ],
                items:[
                    {
                        id:1,
                        url:'/common/moves/ooo.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:2,
                        url:'/common/moves/er.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:3,
                        url:'/common/moves/ooo.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:4,
                        url:'/common/moves/rr.jpg',
                        content:'不知道写什么'
                    }

                ]
            },
            {
                id:3,
                name:'家乡',
                itemname:'相关视频',
                 url:[
                {
                    id:1,
                    url:'/common/moves/lelel.jpg',
                },
                {
                    id:2,
                    url:'/common/moves/hah.jpg',
                },
                {
                    id:3,
                    url:'/common/moves/xixi.jpg',
                }

                ],
                items:[
                    {
                        id:1,
                        url:'/common/moves/ooo.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:2,
                        url:'/common/moves/er.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:3,
                        url:'/common/moves/ooo.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:4,
                        url:'/common/moves/rr.jpg',
                        content:'不知道写什么'
                    }

                ]
            },
            {
                id:4,
                name:'家乡美丽',
                itemname:'相关视频',
                url:[
                {
                    id:1,
                    url:'/common/moves/rr.jpg',
                },
                {
                    id:2,
                    url:'/common/moves/hah.jpg',
                },
                {
                    id:3,
                    url:'/common/moves/xixi.jpg',
                },
                {
                    id:4,
                    url:'/common/moves/ooo.jpg',
                },{
                    id:5,
                    url:'/common/moves/rr.jpg'
                },
                {
                    id:6,
                    url:'/common/moves/xixi.jpg'
                }
                ],
                items:[
                    {
                        id:1,
                        url:'/common/moves/ooo.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:2,
                        url:'/common/moves/er.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:3,
                        url:'/common/moves/lelel.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:4,
                        url:'/common/moves/rr.jpg',
                        content:'不知道写什么'
                    }

                ]
            },
            {
                id:5,
                name:'家乡过年',
                itemname:'相关视频',
                url:[

                    {
                        id:1,
                        url:'/common/moves/hah.jpg',
                    },
                    {
                        id:2,
                        url:'/common/moves/xixi.jpg',
                    },
                    {
                        id:3,
                        url:'/common/moves/ooo.jpg',
                    },{
                        id:4,
                        url:'/common/moves/rr.jpg'
                    },
                    {
                        id:5,
                        url:'/common/moves/xixi.jpg'
                    }
                ],
                items:[
                    {
                        id:1,
                        url:'/common/moves/ooo.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:2,
                        url:'/common/moves/er.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:3,
                        url:'/common/moves/rr.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:4,
                        url:'/common/moves/rr.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:5,
                        url:'/common/moves/xixi.jpg',
                        content:'不知道写什么'
                    },

                ]
            },
            {
                id:6,
                name:'爱的家乡',
                itemname:'相关视频',
                url:[
                    {
                        id:1,
                        url:'/common/moves/ooo.jpg',
                    },

                    {
                        id:2,
                        url:'/common/moves/xixi.jpg',
                    },
                    {
                        id:3,
                        url:'/common/moves/ooo.jpg',
                    },{
                        id:4,
                        url:'/common/moves/rr.jpg'
                    },
                    {
                        id:5,
                        url:'/common/moves/xixi.jpg'
                    }
                ],
                items:[
                    {
                        id:1,
                        url:'/common/moves/ooo.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:2,
                        url:'/common/moves/er.jpg',
                        content:'简介啊时间多久啊设计大赛'
                    },
                    {
                        id:3,
                        url:'/common/moves/rr.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:4,
                        url:'/common/moves/hah.jpg',
                        content:'不知道写什么'
                    },
                    {
                        id:5,
                        url:'/common/moves/xixi.jpg',
                        content:'不知道写什么'
                    },

                ]
            }
        ]
    },
    onInit() {
        this.title = this.title;
    },
    onReady(){
    },
    goback(){
        router.back()
    },
    cancelSchedule(){
        this.$element('simpledialog').close()
    },
    setSchedule(){
        this.$element('simpledialog').close()
    },
    openvideo(name,video){
        router.push({
            uri:'pages/detail/detail',
            params:{
                name:name,
                videoUrl:video
            }
        })
    }
}
